### ISSUE TITLE
Only a few covers added out of hundreds scanned (Jellyfin)

### ISSUE THREAD

**Issue by halpcomputar** [ilarramendi/Cover-Ratings#1]
I'm running CoverRatings on an ubuntu 20.04 server, just testing things out, and I have a paid omdb api. I have all my media on a fairly large union filesystem using mergerfs, so media is stored at /mnt/Merged/TV and /mnt/Merged/Movies, respectively. I have CoverRatings at /home/<username>/CoverRatings.

I ran the command to add my api to CoverRatings, and after running "./CoverRatings '/mnt/Merged/Movies/*'" I got "Cover image saved for ..." for two items, and "No info found" for another. After renaming that third item properly (folder name was misspelled) that item's cover was found as well. This is out of about 900-1000 movies. The cover images for 4 TV series (out of about 350 series) were saved as well. Attempts to re-run the script to hopefully scrape more data have been unsuccessful.

Any help would be greatly appreciated, and I'd be more than happy to provide any other information you need to help troubleshoot.

Edit so that anyone else seeing this can resolve themselves: I found that CoverRatings doesn't want to overwrite any existing poster.jpg files that already exist. After deleting all the poster.jpg files that already exist, I've been able to have it pull the vast majority of the covers for the movies I have. (Some are still missing, but that's to be expected from a WIP project.) This issue can be closed. (Of course the ability to overwrite existing covers, possibly with a prompt would be a welcome future update as well.)

**Comment by ilarramendi** [comment]
Thanks for pointing this out! This would be a usefull feature, thank you!
I just added a parameter to overwrite cover files, i hope you find it usefull.
