### ISSUE TITLE
Image resolution lower on output jpg than original

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#10]
I noticed the output jpg seem to have a lower quality than the original.
Included two example; (one original and one with overlay).

![folder](https://user-images.githubusercontent.com/66222810/116065189-0d5e1f00-a687-11eb-86f4-60043cdc0590.jpg)
![poster](https://user-images.githubusercontent.com/66222810/116065190-0df6b580-a687-11eb-94d8-961c72333026.jpg)

Maybe the jpg quality on 'overlaying'can be set to higher quality?

**Comment by ilarramendi** [comment]
This should be fixed on the last update, also the image width can be changed from the config file!
