### ISSUE TITLE
naming of poster/folder

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#12]
1. Your program writes the files as 'poster.jpg'; 
however when I turn on 'Save images' in the jellyfin server, it defaults them to 'folder.jpg.  Folder.jpg also seems to work fine in Plex. Maybe consider changing your file name from poster.jpg to folder.jpg to avoid 'duplicates'images being by various programs. Folder.jpg seems to be consistent and working across plex, Jellyfin.

2.  Jellyfin also show also different image for 'partially' started movies, in the continue watching. For this jellyfin saves to the media folder a file called: Backdrop.jpg. Is your program also able to download the related backdrop (or use existing) and to apply the overlay? See for example: https://ibb.co/bJRCFjh

**Comment by ilarramendi** [comment]
1: On the last update i changed the name to folder.jpg, as you suggested! It also works fine on emby.
2: Also added this on the last update as you suggested! Im having a problem with this where its only displayed on emby if i delete the automaticaly downloaded image. Also the backdrop isnt the image it shows for partialy watched films, its the background image on the info page! (at least on emby)

**Comment by michpas** [comment]
Hi. Sorry to have to come back on this one.
It indeed seems to be thumb.jpg that jellyfin is using to show 'movies being played' and not the file 'backdrop'; which is indeed the file used in plex to show the background-full screen blurred image, when movie is clicked.
To conclude, the better-cover script indeed need to tackle the 'folder.jpg' and the 'thumb.jpg'.
Backdrop and backdrop references (in for example the config file) can be dropped.
