### ISSUE TITLE
Suggestion: Top/bottom bars do not work with absolute pixel

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#14]
I started to play around with the positioning of the ratings and couldn't really get it correct on top/bottom. 
Sometimes things drop off, in other cases it's partly shown.

This is I think due to the fact that the posters.jpg all have different sizes and using absolute sizes in the config.json maybe leads to a situation where it never really fits. Example are the 4 images below; the bottom bars each have a different cutt-off.

What could really help is maybe to use the following technique; for example on the bottom alignment.
First extract the posterwidth. Than you resize the 'overlay image' that you want on top of it to that dimension. And than you merge them together:
- widthposter=$( exiftool -f -s3 -"ImageWidth" "$flink" )
- convert /config/overlays/overlay_poster.png -resize "$widthposter" /config/overlays/overlay_poster2.png
- convert  "$flink"  /config/overlays/overlay_poster2.png -flatten  "$flink"
This way, irrelevant of poster width, you always get a perfectly aligned bar at the bottom or top where the whole 'overlay'is visible.
I know you are using a different technique with web images; but maybe something in this thinking direction could help. 

![folder](https://user-images.githubusercontent.com/66222810/116465351-6be4f200-a86d-11eb-8d73-4cc07fb9a7e7.jpg)
![folder](https://user-images.githubusercontent.com/66222810/116465361-6edfe280-a86d-11eb-9341-84c9b0e5272f.jpg)
![folder](https://user-images.githubusercontent.com/66222810/116465367-71dad300-a86d-11eb-988e-e38609f13356.jpg)
![folder](https://user-images.githubusercontent.com/66222810/116465376-743d2d00-a86d-11eb-945a-3ddade02acd3.jpg)

**Comment by ilarramendi** [comment]
This should be fixed now, now all images are scalled to the size set on the config file.
There is still the problem where it shows the empty mediainfo bar (img 3), ill fix that in a future release.
PD: to fix the overflowing text on the ratings make the image/text/spaces smaller!
