### ISSUE TITLE
Bug: Folder with video file and trailer. Picks up the trailer movie to extract poster codex information

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#15]
In many videofolder I have two video files. One is the movie and the other is the downloaded trailer. Usually with extention [name]-trailer.mkv
It seems the script is picking up something the real video and sometimes the trailer. Clearly the trailer has different video codecs.
In my example: Mulan is 4k, trailer is 1080p. Posters shows 1080p.
As quick work-around maybe ignore videofiles with *-trailer.* in the name.

**Comment by ilarramendi** [comment]
Should be fixed now, it would be realy usfull if you test this since i dont have any trailer in my collection!

**Comment by michpas** [comment]
Yes, tested and works as expected. It now ignored '-trailer' files.
