### ISSUE TITLE
Question: How to use spoken language setting

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#18]
Great to see all progress
I see you have also done work on the languages Can you explain a bit more how I can use this?
Lets say I want an image overlay, if there is a Dutch spoken language in one of the audiosteams?
I tried adding 'NLD' to the audio string, but with no success. Do I need to add a local image in the /config/local_images/ folder?

    "movie": {
          "mediainfo": {
               "position": "right",
               "alignment": "center",
               "imgSize": "210px",
               "padding": "35px 15px",
               "space": "30px",
               "color": "#1004",
               "config": {
                    "AVC": true,
                    "HD": true,
                    "HDR": true,
                    "HEVC": true,
                    "SD": true,
                    "UHD": true,
                    "UHD-HDR": true,
                    "SDR": true,
                    "UNDEFINED": false
               },
               "audio": "NLD,ENG,SPA,JPN,POR,FRE,ITA,DAN,KOR,RUS,SWE,ZHO,HIN"

**Comment by ilarramendi** [comment]
The image for NLD is not added by default, ill add most common lenguajes in a future Release, for now you can place the flag in media/language/NLD.png and should work!

**Comment by ilarramendi** [comment]
This works by using the first lenguage its written on the config, for example if you have a video with primary audio track english and secondary spanish, if you set audio to: SPA,ENG it will show the first language found (SPA)

**Comment by michpas** [comment]
Hi. thanks. Trying.

Have added the following to teh config file; as I want it show if the Dutch language is available
                         "audio": "NLD,DUT,ENG,SPA,JPN,POR,FRE,ITA,DAN,KOR,RUS,SWE,ZHO,HIN"
         I also put in the /media/language/ t files NLD.png and DUT.png (both a dutch flag).
The file specs are below; specifies language: : Dutch

But when I run it, the image doesn't show the flag. Not sure why.

File specs:

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 45 min
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 289 MiB (10%)
Title                                    : NL
Language                                 : Dutch
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

**Comment by ilarramendi** [comment]
Can you run this command and post the output?
`ffprobe "path/to/file.mkv" -of json -show_entries stream=index,codec_type,codec_name,height,width:stream_tags=language -v quiet`

**Comment by michpas** [comment]
Hi. Before I execute the command. I did play around the function a bit more.
and can now see that your script does pick up 'dutch' as a language and I can see in the overlay it tries to show an image.
However it looks like the image is not found and it shows an empty block.
![folder](https://user-images.githubusercontent.com/66222810/116794336-984a7980-aacc-11eb-8131-d56f9db9fbcd.jpg)

I guess there is something wrong with my image folder or permissions or naming.

Thinking of this and making it simpler.
Would it be possible to simply download all default images  you currently use in the /config/images/ folder?
The same as you do with the config.sys file.

This would very easily allow people to either replace images with their own, learn from your images or add (in case of languages) and not having to put effort in new folders, permissions, naming etc.

**Comment by ilarramendi** [comment]
Changed `-c` param to `-wd` in the last relese, run the executable/docker with that param set to a directory and all images and config file should appear and be persistent there!
(Also added dutch language by default, the flag is located in `media/languages/NLD.png`)

Docker build is still in progress, you might want to wait some time to pull the container again!

**Comment by ilarramendi** [comment]
Also it would be usefull if you execute the command to know what 3 letter iso code ffprobe uses to represent dutch language

**Comment by michpas** [comment]
Hi. I ran the script. Included below the outcome.                 "language": "dut"                

{                                                                                                                                                              
    "programs": [                                                                                                                                              
                                                                                                                                                               
    ],                                                                                                                                                         
    "streams": [                                                                                                                                               
        {                                                                                                                                                      
            "index": 0,                                                                                                                                        
            "codec_name": "h264",                                                                                                                              
            "codec_type": "video",                                                                                                                             
            "width": 1920,                                                                                                                                     
            "height": 1080,                                                                                                                                    
            "tags": {                                                                                                                                          
                "language": "eng"                                                                                                                              
            }                                                                                                                                                  
        },                                                                                                                                                     
        {                                                                                                                                                      
            "index": 1,                                                                                                                                        
            "codec_name": "ac3",                                                                                                                               
            "codec_type": "audio",                                                                                                                             
            "tags": {                                                                                                                                          
                "language": "dut"                                                                                                                              
            }                                                                                                                                                  
        },                                                                                                                                                     
        {                                                                                                                                                      
            "index": 2,                                                                                                                                        
            "codec_name": "mjpeg",                                                                                                                             
            "codec_type": "video",                                                                                                                             
            "width": 1024,                                                                                                                                     
            "height": 602,                                                                                                                                     
            "tags": {                                                                                                                                          
                                                                                                                                                               
            }                                                                                                                                                  
        }                                                                                                                                                      
    ]                                                                                                                                                          
}

**Comment by ilarramendi** [comment]
Ok then it should work changing NLD to DUT in the icon and config.json, ill fix this in the next release!

**Comment by michpas** [comment]
Hi. I got the NL language tag working !!
Thanks for the design and tips. it's indeed 'DUT' and with the DUT image in the folder, it works !

I did replace the flag with a text 'NL gesproken; which basically states: 'dutch spoken'.
This works really well.

I have also experimented with replacing the RT 2d with 3d. See included.
![folder](https://user-images.githubusercontent.com/66222810/116796154-b028fa00-aada-11eb-88dc-8fedbc741e98.jpg)

And last but not least an example of a 4kHDR movie
![folder](https://user-images.githubusercontent.com/66222810/116796170-d484d680-aada-11eb-8a1d-dd91be3b066d.jpg)

I experimented with different layouts; but for me, this seems to work really well.

Thanks again

**Comment by memnos** [comment]
> Hi. Before I execute the command. I did play around the function a bit more.
> and can now see that your script does pick up 'dutch' as a language and I can see in the overlay it tries to show an image.
> However it looks like the image is not found and it shows an empty block. see bottom right in the image
> ![folder](https://user-images.githubusercontent.com/66222810/116794336-984a7980-aacc-11eb-8131-d56f9db9fbcd.jpg)
> 
> I guess there is something wrong with my image folder or permissions or naming.
> 
> Thinking of this and making it simpler.
> Would it be possible to simply download all default images you currently use in the /config/images/ folder?
> The same as you do with the config.sys file.
> 
> This would very easily allow people to either replace images with their own, learn from your images or add (in case of languages) and not having to put effort in new folders, permissions, naming etc.

@michpas 
Could you provide .css file as you modified to have ratings on the top?

**Comment by michpas** [comment]
It's 2 css sheets. Have added them both

https://filebin.net/44muk2vbu67sc20b

File cover.css is in the main folder
and newCover.css in the /media/covers/ folder.

This creates:
![image](https://user-images.githubusercontent.com/66222810/124077225-9018a700-da47-11eb-8786-d878e939bc94.png)

**Comment by memnos** [comment]
Thank you.
Do you maybe also know if it is possible to use posters in other language different from english

**Comment by memnos** [comment]
@michpas
sorry if i write to you, but it seems none is looking at this project.
It seems that only tmdb ratings are added, can you confirm? 
Tnx

**Comment by michpas** [comment]
Hi. The project is fully working. I have it visualizing: imdb, Rotten tomatoes critics and rotten tomatoes audience.

![image](https://user-images.githubusercontent.com/66222810/124599799-59d39100-de66-11eb-82e4-2cfe15a22e84.png)

I think the default (complete new install) starts with showing 3 or 4 different ratings. Maybe try that?

**Comment by memnos** [comment]
@michpas 
Mhh, there must be something wrong.
I made a fresh install and let all config as dofault, but i have just tmdb rating.
Here is my picture.

Maybe i need different api from OMDB?

Here is how i start docker:

docker run -i --rm \
  -v /opt/better-covers:/media \
  -v /opt/better-covers:/config \
  -e a=true \
  -e w=20 \
  -e omdb=50ec4afc \
  -e v=2 \
  ilarramendi/better-covers 

Any idea?

![folder](https://user-images.githubusercontent.com/25641404/124603445-3b6f9480-de6a-11eb-92b9-8ffea2a7dc3c.jpg)

**Comment by michpas** [comment]
I also have a tmdb key added.
Can you try that?

**Comment by memnos** [comment]
@michpas 
This is really really strange.
i deleted beter-cover dir, than run docker like this:
```
docker run -i --rm \
  -v /opt/better-covers:/media \
  -v /opt/better-covers:/config \
  -e a=true \
  -e w=20 \
  -e omdb=xxxx \
  -e tmdb=xxxx \
  -e v=2 \
  ilarramendi/better-covers 
```

But in my poster i just see tmdb rating as before.
To make a fresh install is it enough to delete the dir where better-cover is installed, in my case /opt/better-covers?

In db.json file i see:
`       "/media/12 anni schiavo (2013)": {
              "ids": {
                     "TMDBID": "76203",
                     "IMDBID": "tt2024544"
              },
              "path": "/media/12 anni schiavo (2013)",
              "title": "12 Years a Slave",
              "year": "2013",
              "seasons": {},
              "type": "movie",
              "metadataDate": "08/07/2021",
              "mediainfoDate": "08/07/2021",
              "releaseDate": "18/10/2013",
              "productionCompanies": [
              ],
              "certifications": [],
              "ageRating": "R",
              "ratings": {
                     "TMDB": {
                            "icon": "TMDB",
                            "value": "7.9"
                     }
              },
`

So with only TMDB ratings, but i don't know why i cannot have other ratings.

**Comment by michpas** [comment]
Hi. Sorry, i also dont know. Can only say it works on my side.
Maybe try:
1. shouldnt your mapped media and config file link to differen folders?
2. Did you also delete the poster.jpg file so you are 100% sure the system generated a new one? 
3. Have you tried other movies/posters? All the same results?

**Comment by michpas** [comment]
Hi.
I have also added the same movie. When the coverscript runs I do get multiple rating.
![image](https://user-images.githubusercontent.com/66222810/125164914-eea2fb00-e194-11eb-9d47-ca88007e78ee.png)

There must be something about your config.

**Comment by memnos** [comment]
@michpas 
Tnx for all this info.
I really don't know what esle to try.
That last thing i can ask is if you can give me your docker file and config file to compare with mine. Obviously deleting your personal data.
It would be great.
