### ISSUE TITLE
Suggestion: Would it also be possible to overlay based on a certain file location?

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#19]
Hi

Maybe another suggestion: Some people (me included) have their movies organized in folders with certain purposes; For example /media/kids; really important they can see which movies are for them :-)

You now have the functionality to place overlays based on rating or video codec information.
Would it also be possible, based on a certain text in the folder name to place an overlay image?
For example if '/kids' is part of the moviefolder than this movie should always get a certain overlay image? Maybe the image can be stored in teh /config/local-images folder. Clearly this needs to be transparant overlay (.png)

Below an example
![idea](https://user-images.githubusercontent.com/66222810/116776487-f47bb200-aa68-11eb-9e44-963b1a147909.jpg)

**Comment by ilarramendi** [comment]
Done!
