### ISSUE TITLE
Windows executable? (and Mac?)

### ISSUE THREAD

**Issue by leshokunin** [ilarramendi/Cover-Ratings#2]
I see you have made an executable. Looks like a Linux one. Would you consider making a Windows exe?

**Comment by ilarramendi** [comment]
Pyinstaller dosnt support cross-compiling, and because i dont have a windows pc atm i cant do this, this can be done with wine too, ill take a look at that later.
For now if you have python installed in your windows pc you can run the script like: 
`python3 CoverRatings.py '/movies/*'`

**Comment by leshokunin** [comment]
There’s gotta be another way to take this Python script and make an exe of
it though?

**Comment by leshokunin** [comment]
I just thought: maybe Docker would be a good alternative. Wdyt?

**Comment by ilarramendi** [comment]
Sorry for not answering!
ATM i dont think ill add a windows executable, but just added docker support!
