### ISSUE TITLE
suggestion: storage location of local images in docker

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#20]
Local images/assets

I read on the wiki page : Replacing Assets. Assets can be placed inside a folder called media next to the executable/script, paths have to be the same as here. If a file is not found it uses the one stored inside the executable

Would it be possible to use the /config folder? This one stays also persistant when refeshing a docker and the media folder is the main folder for all movies. Would be better to have any files that are required by a docker script in the /config/ folder 
Maybe somethine as /config/local-images/

**Comment by ilarramendi** [comment]
Should be working like this now, try the `-wd` parameter (or `-e wd` enviromental variable for docker)

**Comment by michpas** [comment]
Hi. Great thanks.
Downloaded the latest docker. Added -e wd /config as parameter.
On a clean start.
The script first downloads the config.sys and than stops.

It's only on the 2nd run that the script actually downloads all the images.
 
Wouldn't it be better if all these files in the wd directory (images etc) all show up in the 1st run?
