### ISSUE TITLE
suggestion: Add: Rotten Tomatoes Audience score

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#23]
You currently have implemented Rotten Tomatometer score.  Would it also be possible to extract the rottentomatoes 'AUDIENCE SCORE'?

![download](https://user-images.githubusercontent.com/66222810/116788517-4f81c900-aaaa-11eb-94c8-3ec0008a19b5.png)

**Comment by ilarramendi** [comment]
The problem with this is that it would need a RT api key, since ATM we download RT ratings from OMDB, and it only provides tomatometer socre.
Its possible to add any ratings provider, but in my opinion having a lot of api keys is not a great solution!

**Comment by michpas** [comment]
ai. so accessing Rotten Tomatoes audience score is not possible via API. That is too bad.
Here is a python script from April 2021, which seems to be able to scrape the user-score.
https://pypi.org/project/rotten-tomatoes-scraper/
Maybe an idea to use this for the time being?

**Comment by ilarramendi** [comment]
I dont realy love the idea of scraping, but it would allow having ratings without api keys and downloading textless posters from some websites, ill take a look at this!

**Comment by ilarramendi** [comment]
Just pushed an update with this and some other nice new features like metacritic must-see!
