### ISSUE TITLE
suggestion: Changing Rotten tomatoes icon depending on score,in line with RT, 

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#25]
For the Rotten tomatoes indicator, it would be really cool to use the formal  '3d' icons that also change, depending on the score
![icons-v2](https://user-images.githubusercontent.com/66222810/116793576-cf6a5c00-aac7-11eb-8ae0-c6a2f9cc6d2f.png)
![image](https://user-images.githubusercontent.com/66222810/116793628-1b1d0580-aac8-11eb-94e8-9784ab83046a.png)

A green splat indicating rotten status, is displayed when less than 60% of the reviews are positive. 
A red tomato score indicating its fresh status, is designated when at least 60% of the reviews are positive. 
Certified fresh

and if the audience score is added; a popcorn full or popcorn green/falling icon, depending on consumer score.

**Comment by ilarramendi** [comment]
Added splat icon, still using 2d icons since these are the oficial icons i found on the page: https://www.rottentomatoes.com/about

**Comment by michpas** [comment]
Thanks. I guess I can still 'overwrite' the icons with 3d icon's, if I place them into that new -wd folder?

**Comment by ilarramendi** [comment]
Yes! the paths inside the -wd folder are:
`media/ratings/RT.png`
`media/ratings/RT-SP.png`
