### ISSUE TITLE
improvement: Using additional information in  .nfo file to always get the correct cover

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#26]
I had the docker run for 250+ movies. Allmost all matched really well. Howvever a few didn't; and wrong covers where fetched (from other movies)
The reason is that in these cases the date in the folder is different in Radarr than in the online databases. Sometimes just off by 1 year or there 2 movies with similar names and same year

To overcome this, another improvement would be to check if there is an .nfo file in the moviefolder.
This file is a standard, used by yellyfin, Kodi etc to store all meta data of the movie
I have added an example nfo file.
This has a line item:
  <imdbid>tt7125774</imdbid>
  <tmdbid>483983</tmdbid>
for your script, in the omdb query, you can add the imsb ID (eg tt.xxxxx); this would always give you a 100% match.
and similar to the tmbd

Without this information, radarr downloads it as : Balloon (2018) and your script download the wrong cover.

To avoid this; if there is an .nfo file in the folder scan for imdbid an/or tmdbid tag. If available, always use this tag in API query (no need to use file name+year)

[Ballon.2018.1080p.BluRay.x264-WiKi-WhiteRev.nfo.zip](https://github.com/ilarramendi/Cover-Ratings/files/6410216/Ballon.2018.1080p.BluRay.x264-WiKi-WhiteRev.nfo.zip)

**Comment by ilarramendi** [comment]
> Ballon.2018.1080p.BluRay.x264-WiKi-WhiteRev.nfo.zip
This file was generated by jellyfin? i dont have save metadata as nfo enabled in emby so no idea how the nfo looks like.

**Comment by michpas** [comment]
Hi. Yes, Jellyfin created it; but it's a industry standard. Kodi also can create and use it.
In Emby you can also enable it: https://emby.media/community/index.php?/topic/51750-what-is-the-use-of-nfo-files/

If the nfo file is there, ideally the imdb and omdb query should query this number and not the folder name+year. This also solved the 5% mismatches.

The issue sometimes occurs in poster covers (like the ballon example above)
But it sometimes also happens with ratings. An example is the gentlemen; according to radarr (and plex) is this 2019.
But on rotten tomatoes there is only a the gentlemen 2020; so there is no rating retrieved.
another nfo example attached.
Where you can see included:
  <imdbid>tt8367814</imdbid>
  <tmdbid>522627</tmdbid>

[The.Gentlemen.2019.2160p.UHD.Remux.HEVC.HDR.Atmos.TrueHD.7.1-playBD-AlteZachen.nfo.zip](https://github.com/ilarramendi/Cover-Ratings/files/6412185/The.Gentlemen.2019.2160p.UHD.Remux.HEVC.HDR.Atmos.TrueHD.7.1-playBD-AlteZachen.nfo.zip)

Hope this helps to test.
If this works, it will fix the 5%-10% mismatches in cover posters and unavailability of ratings for movies that have 'different release years' in different systems.

**Comment by ilarramendi** [comment]
Should be fixed on the latest version (`ilarramendi/cover-ratings:develop`), it will allways use the IMDBID or TMDBID if found.
It would be apreciated if you could test it since i dont want to change the metadata to the media drives on my system!

**Comment by ilarramendi** [comment]
Pushed to main branch, closing pr
