### ISSUE TITLE
Just some reflections...

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#34]
Hee. Really nice job.
All works extremely smooth. Am now running it on a few folders with different settings and results look really great.
Wonderful that you were able to pull in so many other review sites.

Why not share this product as is a bit more on various socials/reddit etc? I think people will love it !

**Comment by ilarramendi** [comment]
Thank you for your feedback! we are aproaching v1 and that will be the first official version not WIP, thats when i have planned start to share the project a bit more!  
Also i have planned to rework the config file to remove most of the visual settings like alignment, padding, etc from there and also remove overlays, to give more importance to the cover files and have the hability to use a custom cover if it has certain properties, ex: 4k UHD and also in /kids folder has a specific cover
