### ISSUE TITLE
really nice

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#36]
Hi. Wanted to let you know.
Really nice output. Sharing an example of the 4K movies.
https://ibb.co/7ynz0hS

and an example of how I have 'tagged' my movies for the kids with local language
https://ibb.co/qmGP5fX

customizations :
I have made the background color on ratings darker, so easier to read.
Changed the rating to more '3d-stylish' images. Happy to share if you wish
Added the 4KHDR tag without background.

**Comment by ilarramendi** [comment]
Looks realy nice, sorry this is no longer working in v0.9 :(
