### ISSUE TITLE
New version. New poster-thumb file on every run?

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#42]
Hi.
Wow. lots of new features. That will take some good time to test.

On the first run I can see it generated backdrop, thumb and folder png images and this indeed took the time it needed.
The 2nd run was much faster; but what I expected is that, (as the files are also older) that no new backdrop thumb or folder file would be written (eg. there is no change).
I do see in the file modification date/time that new backdrop, thumb and folder were created.
Is that caused by the fact I have  'overwrite option' to yes?
If so, setting this to 'no', would that work? Because ultimatelty I do want the images to be overwriten, but only actually when there is a change in rating or image outcome (eg. triggered by the forced 'duration' days algoritm

Thanks for helping me understand.

**Comment by ilarramendi** [comment]
Hello, indeed thats because you have overwrite enabled, on the next update ill add another flag to only update covers if they were generated by the script and with different settings, most of the work for that was already done on v0.9

**Comment by michpas** [comment]
ah yes. So am I correct overwrite means:

Overwrite: yes: Always create new poster files on the local storage , but do no query the websites for rating. Only query the websites to create new posters, based on the build in refresh-logic (# days passed)
Overwrite: no: Never create new poster files on the local storage if existing, but do query the websites and create posters (and overwrite), based on the build-in refresh logic. (# days passed)

Is this correct? Maybe good to capture on your information site. Very useful

**Comment by ilarramendi** [comment]
Almost correct:
Every run downloads missing ratings and gets mediainfo if needed (with the logic we discussed on previous pr).
If overwrite is enabled it overwrites any file.
If overwrite is disabled it only generates a cover if no cover is found.
On the future with the new flag it would allow to only generate images for missing covers or existing covers with different settings/ratings/mediainfo.
Ill add this to the Readme probably.

**Comment by ilarramendi** [comment]
https://github.com/ilarramendi/Cover-Ratings/releases/tag/v0.9.1-linux
Added `-a true` parameter to only overwrite covers generated by the app with different settings, also improved speed a lot!

**Comment by michpas** [comment]
Thanks. Tested it. with overwrite to false and -a true
Works fine as I can test. Ofcourse will still need to test if the posters get updated according to the schedule; but will let you know in due time, when they are up for refresh
