### ISSUE TITLE
image files too large?

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#43]
The filesize for the poster, thumb and folder is around 32 MB each.  Not sure why this is so big? Is that due to the png format?
In your previous version, the posters generated were around 2 a 3 mb and thumb 0.5 mb.

![image](https://user-images.githubusercontent.com/66222810/118393633-5c70f180-b640-11eb-93b8-7253ba29898c.png)

**Comment by ilarramendi** [comment]
That and te fact that i resized the image to be double the size, maby ill switch back to jpg since i wasnt able to enable transparency yet

**Comment by michpas** [comment]
yeah. png did work (as did jpg); but I think a 90% smaller size for these images is definately a good thing. As all these visuals will need to be loaded into libraries players; better keep is to 'normal' sizes. Can't predict what 30 mb files do if people have 1000's of videos and theiy players.

**Comment by ilarramendi** [comment]
Switched to jpg and image size is almost the same, will stay with png for now.
Maby the image size that you are thinking is with a image of half the width and height of older versions, wich would have more than double of the size.
This can obviously be changed adjusting the image size in the html file!

**Comment by michpas** [comment]
Hi. 
You solved it. The file sizes are now back to normal sized eg. ~2 MB per file.

![image](https://user-images.githubusercontent.com/66222810/118537172-ea3a0300-b74c-11eb-82a6-0fecb8783fa6.png)
