### ISSUE TITLE
Question: Struggle with changing 'positioning and background color'

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#45]
Hi. I have been trying to figure out how to do some simple changes, but struggle with it.
Maybe you can help and also post an example on your wiki?

For example: 
- for a standard movie poster file, how do I change the location in a poster.jpg of rating or mediainfo bar from top/bottom/left/right 
- And how do I change the background color of a certain bar in a poster to fully transparant?

**Comment by ilarramendi** [comment]
Hello! On the last version i removed visual configurations from the config file to allow for more customization, all visual settings can be done editting the corresponding html/css files, or creating new ones.
Standard locations are no longer pre-coded but the HTML/CSS code for the old cover is available [here](https://github.com/ilarramendi/Cover-Ratings/tree/v0.8-linux).
The cover used for each media is defined on [covers](https://github.com/ilarramendi/Cover-Ratings#covers).

**Comment by michpas** [comment]
Hi. Thanks. I did try to modify the standard html/css, but realize im not familiar with css. Tried for quite.some time, but results were not as ecpected. 
Are you sble to create a html/css version with ratings to bottom and media info to right
And with mediainfo fully transparant?
This wsy i can.learn by looking whats changed

Thanks

**Comment by ilarramendi** [comment]
Sure! Having a couple of examples was always the idea, will add this on next release!

**Comment by michpas** [comment]
Great, thanks!
Image example included:
*)Ratings on top. with transparancy color "#1009"
*) and mediainfo at bottom; bottom part fully transparant
https://ibb.co/7ynz0hS

And one with mediainfo at top: fully transparant
and ratings at bottom with transparancy color "#1009"

I liked the way how you did the 'fresh'sticker on stylesheet; but I can work our that example myself :-)

**Comment by michpas** [comment]
Hi ilarramendi,

If you have the time to create the 2 style sheets above, i can also continue testing and provide more feedback.

Your product is very close to final :-)

**Comment by ilarramendi** [comment]
Hello! Im having very little time these days, looking into crypto and my studies, will get back to this in a couple of days!
Have a great day!

**Comment by michpas** [comment]
Hi. thanks for letting me know. Good luck with the study and the coins.

Good news, with trial and error I have managed to modify the style sheets. Have now got a very nice setup. Thanks again for the great work
