### ISSUE TITLE
Cover Art Options

### ISSUE THREAD

**Issue by Protektor-Desura** [ilarramendi/Cover-Ratings#6]
Any chance you could edit the script to support putting a graphic at the top like the Emby Cover Art plugin does? Sort of make it look like a DVD case or Bluray case or Music CD case.

https://emby.media/community/uploads/inline/3/525405ee5b148_f0789cfc6a1ffa8246b48bc64595dee6.png
https://emby.media/community/uploads/inline/3/525404df6db2b_3bae52c8c9e53743c0f86a71ae6347d8.png
https://emby.media/community/uploads/inline/3/5254075490614_28b9beecca6f92e7c144e45037b30a3c.png
https://emby.media/community/uploads/inline/232947/5b6a3665ddaa3_movies.jpg

Or even show disc images with poster if they are downloaded, like this.
https://imgur.com/1HaHAtB

You can tell Jellyfin to download images of the discs if they are available, then you could use them to make the above image.

**Comment by ilarramendi** [comment]
Hello! I dont think collections is something the script is going to support in the near future, on the other hand i could add a case like bluray or dvd, do you think that should be added to all movies when enabled or specifically filter which movie are blueray for example (no idea how to do that)

**Comment by Protektor-Desura** [comment]
I would add it to all movies that are that in format. With Radarr you can put the source in the filename so your only option is to search the filename and see if it has DVD, Bluray or WEBRip, WEB-DL in the filename, in order to know what type of cover to use. Trying to do filters for specific movies sounds like a pain in the ass to me personally to code.

**Comment by Protektor-Desura** [comment]
You can use also use ffprobe to get the resolution of the video file as well.

**Comment by ilarramendi** [comment]
> You can use also use ffprobe to get the resolution of the video file as well.  

Done!

> DVD, Bluray or WEBRip, WEB-DL in the filename  

Ill probably add something like this in a future release, need to find the icons and have a couple of things to fix first!
