### ISSUE TITLE
Feature request: a script that integrates with Radarr 'add connection-custom scripts'

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#7]
Radarr as a feature called: 'add-connection'; where a custom script can be run on a certain event; 
for example: on import or on upgrade.

It would be great if this script can be run/executed on this event so that it only executes for the one movie that is actually being imported at the moment; results in directly a poster.jpg as soon as the file is available and doesn't scan all folder/files if not needed

**Comment by ilarramendi** [comment]
Using the script with a single folder is possible, the problem is adding the script and the dependencies to the container from radarr/sonarr, this will create the need to make a custom container based on the image from linuxserver, ill take a look at that now!

**Comment by ilarramendi** [comment]
```
FROM linuxserver/radarr
RUN apt-get -y update
RUN apt-get install -y cutycapt xvfb mediainfo ffmpeg wget
RUN wget 'https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.6-linux/BetterCovers' -q
RUN chmod +x '/BetterCovers'
RUN mkdir /tmp/runtime
RUN chmod 0700 /tmp/runtime
ENV XDG_RUNTIME_DIR /tmp/runtime
```
Got the script to work inside the docker container with this dockerfile, ill push the radarr and sonarr dockerfiles and script to automaticaly generate covers tomorrow!

**Comment by michpas** [comment]
Hi.
I'm aware there are at least three ways of getting a custom 'script insight a docker'. Not sure what is the best option for this purpose. Maybe you have a view.
1.  Linuxserver dockers allow  'docker mods' https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
An example I use is: https://github.com/SimpsomRJ/docker-bazarr-mod-subsync where the bazarr-mod-docker is added as an environmental variable. So when radarr is repulled/installed, it will automaticly pull the add-on docker and install it. From bazarr these scripts in the add-on docker can be called as it's all in one installed instance.

2,. LinuxServer also allows scripts to be run on install. All scripts placed in the /config/custom-cont-init.d folder of main docker will be executed. In this case no docker container (for the add-on) needed.
For example in the radarr /config/custom-cont-init.d/ folder 
 a file 'install_cover_ratings.sh' that contains all your installation steps.

3. Creating a whole new docker that pull radarr in.

Not sure what the best option is wrt flexibility, usability etc; but thought I let you know.
