### ISSUE TITLE
Feedback on docker

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#9]
Hi. I also tried the docker. Below my experience and feedback&suggestions. Hope you find this helpful.

Docker installed great.

Below my experience.

1. I'm using the synology docker interface. Could easy map the 'media' folder; however couldn't map the individual link to the config.json file (as it wasn't there on initial install); Suggestion: Maybe it's possible to map a  'config' folder, link Radarr/Sonarr; instead of to the file.  So docker/better-covers to /config folder. And on the first run of the docker, the system could create a config file in this folder. (-v /path/to/data:/config \)
Work around at this moment, manually downloaded the config.json and put it in the docker/better-covers folder.

2. The two API keys were ofcourse initially missing. Would be great if these can be added to the docker environmental setup. So making it possible to add  (-e TMDBApiKey = abcdef and -e OMDBApiKey = xyz). This would also allow in the first run to correctly create the config.json with the information.
Work around, I added these keys manually into the config file.

When executed it worked !!. From the 4 test movie folders, I could see it has created two covers.
A couple of interesting findings.
1.  Your program writes the files as 'poster.jpg'; however jellyfin when downloading cover images writes them as 'folder.jpg. I check other movies; they all have 'folder.jpg' and not 'poster.jpg'.  Folder.jpg seems to work fine in jellyfin and Plex. Maybe consider changing file name to avoid 'duplicates' with other programs?

2. Plex and Jellyfin, show also images for 'partially' started movies. For this they use a file called: Backdrop.jpg. Is your program also able to download the related backdrop and also apply the overlay?

3. See included image for output log. Interestingly it starts with 'erro is mediainfo installed', but than works fine for two files.
![output](https://user-images.githubusercontent.com/66222810/116061891-aa1ebd80-a683-11eb-87fa-6533129d637a.jpg)

4. It only processed 2 out of the 4 movies.  It missed: Dunkirk (2017) and  Star Wars The Rise of Skywalker (2019); although Jellyfin does find the related cover images. Makes me wonder, is there something in the algoritme that is different from the Jellyfin downloading covers? Couldn't it find the image?  

5 . Maybe another idea is: Where there is already a local folder.jpg and local backdrop to use these images; this way users can also use their own and they don't get overwritten by your script. You can simlpy rename the existing folder.jpg to folder_original.jpg and create your overlayed one.

6. I don't think it's needed to 're-do'every poster on everyrun. As some movie databases are very large. Maybe you can add a parameter that indicates 'reprocess' time (eg. #days in between). Each processed JPG file would be 'tagged' with a data on which it was processed and thus can be skipped untill the 'time is passed'. As an idea: I used the following to add '' exiftool -creatortool="993" -overwrite_original "$flink"'' This 993 code indicated the file was already processed. In your case, this could be a date value. Ps. For fun, here is the posting on my original attempt: https://www.reddit.com/r/jellyfin/comments/iwlty6/jellyfin_coverart_overlay/

7. It would be great to be able to run the docker in 2 variances:
One variance is to have it periodicly run. A bit like amtd -collects trailers - (https://github.com/RandomNinjaAtk/docker-amtd) with -e AUTOSTART=true and -e SCRIPTINTERVAL=1h. This runs teh docker and on every interval the scripts executes. P.s building on point 6 above, this script also needs to capture what has been processed to avoid redl's trailers; for this he created a simple file in teh config folder with the IMDB number of the movie. If it exists it doesn''t process again. 
The other is without the autostart, so on individual parameter lines. In the future enabling Radarr/Sonnar connect link.

I think your program/script has great potential, hope this information above helps to make it even better.
Keep up the great work.

**Comment by ilarramendi** [comment]
1, 2, 4: Fixed!
3: Changed error message, this happend when there is a problem getting the mediainfo for the file.
5: Using existing images is already a planned feature!
6: ATM the script is not polish enought to be run as a service IMO, aditionaly you can run the script without the -o flag and it wont procces the movies that already have a poster. The 993 tag thing looks interesting, ill take a look at that later!
7: When the script is a bit more completed ill release a way to periodicaly run it and download covers!

Thanks for the feedback!!!
